default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages: [pre-commit]

repos:
# BASIC CONF FOR ALL PRE-COMMITS REPO TYPE
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Git style
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-merge-conflict
      - id: forbid-submodules

      # Common errors
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      # Cross platform
      - id: mixed-line-ending
        args: [--fix=auto]

      # Security
      - id: detect-private-key
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        exclude: applications/site-web-application/js/new_relic.js
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.2
    hooks:
      - id: golangci-lint